import {
  ValidationError,
  JOURNAL_NOT_BALANCED,
  MINIMUM_TWO_LINES_REQUIRED,
  JOURNAL_LINE_ZERO_AMOUNT,
  JOURNAL_LINE_BOTH_SIDES,
  INVALID_STATUS_TRANSITION,
  ENTRY_VOIDED_IMMUTABLE,
  ENTRY_SYSTEM_GENERATED_IMMUTABLE,
} from "@/features/shared/errors";

// InvalidMonetaryAmount + INVALID_MONETARY_AMOUNT viven en
// modules/shared/domain/errors/monetary-errors. Importar desde allí.

export const INVALID_JOURNAL_STATUS = "INVALID_JOURNAL_STATUS";

/**
 * Module-internal aliases for legacy shared codes — kept for symmetry with the
 * other module-error constant exports. The classes below emit the SAME wire
 * codes as legacy so the C4 shim is a thin pass-through (same precedent as
 * Payment with INVALID_STATUS_TRANSITION and ENTRY_VOIDED_IMMUTABLE).
 */
export const JOURNAL_VOIDED_IMMUTABLE = ENTRY_VOIDED_IMMUTABLE;
export const JOURNAL_AUTO_GENERATED_IMMUTABLE =
  ENTRY_SYSTEM_GENERATED_IMMUTABLE;

// ── I1: partida doble ──

export class JournalNotBalanced extends ValidationError {
  constructor() {
    super(
      "El asiento no está balanceado: la suma de débitos debe ser igual a la suma de créditos",
      JOURNAL_NOT_BALANCED,
    );
  }
}

// ── I2: mínimo 2 líneas ──

export class JournalMinLines extends ValidationError {
  constructor() {
    super(
      "El asiento debe tener al menos dos líneas",
      MINIMUM_TWO_LINES_REQUIRED,
    );
  }
}

// ── I10: una línea — sin both-sides + sin zero ──

export class JournalLineZeroAmount extends ValidationError {
  constructor() {
    super(
      "El monto de la línea debe ser mayor que cero",
      JOURNAL_LINE_ZERO_AMOUNT,
    );
  }
}

export class JournalLineBothSides extends ValidationError {
  constructor() {
    super(
      "Una línea no puede tener débito y crédito al mismo tiempo",
      JOURNAL_LINE_BOTH_SIDES,
    );
  }
}

// ── I5: status transitions ──

export class InvalidJournalStatus extends ValidationError {
  constructor(value: string) {
    super(`Estado de asiento inválido: ${value}`, INVALID_JOURNAL_STATUS);
  }
}

export class InvalidJournalStatusTransition extends ValidationError {
  constructor(from: string, to: string) {
    super(
      `La transición de estado de asiento de ${from} a ${to} no está permitida`,
      INVALID_STATUS_TRANSITION,
    );
  }
}

// ── I7: VOIDED inmutable (terminal). C2-FIX-2 parity: every transition out of
//        VOIDED surfaces ENTRY_VOIDED_IMMUTABLE, mirroring legacy
//        validateTransition's first branch.

export class CannotModifyVoidedJournal extends ValidationError {
  constructor() {
    super(
      "Un documento anulado no puede ser modificado",
      ENTRY_VOIDED_IMMUTABLE,
    );
  }
}

// ── I9: auto-generated (sourceType !== null) inmutable vía la API contable.

export class JournalAutoGeneratedImmutable extends ValidationError {
  constructor() {
    super(
      "Los asientos generados por el sistema no pueden ser modificados desde la API contable",
      ENTRY_SYSTEM_GENERATED_IMMUTABLE,
    );
  }
}

// Re-export para que el módulo importe códigos por canal único.
export {
  JOURNAL_NOT_BALANCED,
  MINIMUM_TWO_LINES_REQUIRED,
  JOURNAL_LINE_ZERO_AMOUNT,
  JOURNAL_LINE_BOTH_SIDES,
  INVALID_STATUS_TRANSITION,
  ENTRY_VOIDED_IMMUTABLE,
  ENTRY_SYSTEM_GENERATED_IMMUTABLE,
};
