import {
  ValidationError,
  JOURNAL_NOT_BALANCED,
  MINIMUM_TWO_LINES_REQUIRED,
  JOURNAL_LINE_ZERO_AMOUNT,
  JOURNAL_LINE_BOTH_SIDES,
  INVALID_STATUS_TRANSITION,
  ENTRY_VOIDED_IMMUTABLE,
  ENTRY_SYSTEM_GENERATED_IMMUTABLE,
  AUTO_ENTRY_VOID_FORBIDDEN,
  FISCAL_PERIOD_CLOSED,
  JOURNAL_DATE_OUTSIDE_PERIOD,
  ACCOUNT_NOT_POSTABLE,
  CONTACT_REQUIRED_FOR_ACCOUNT,
} from "@/features/shared/errors";

// InvalidMonetaryAmount + INVALID_MONETARY_AMOUNT viven en
// modules/shared/domain/errors/monetary-errors. Importar desde allí.

export const INVALID_JOURNAL_STATUS = "INVALID_JOURNAL_STATUS";

/**
 * Module-internal aliases for legacy shared codes — kept for symmetry with the
 * other module-error constant exports. The classes below emit the SAME wire
 * codes as legacy so the C4 shim is a thin pass-through (same precedent as
 * Payment with INVALID_STATUS_TRANSITION and ENTRY_VOIDED_IMMUTABLE).
 */
export const JOURNAL_VOIDED_IMMUTABLE = ENTRY_VOIDED_IMMUTABLE;
export const JOURNAL_AUTO_GENERATED_IMMUTABLE =
  ENTRY_SYSTEM_GENERATED_IMMUTABLE;

// ── I1: partida doble ──

export class JournalNotBalanced extends ValidationError {
  constructor() {
    super(
      "El asiento no está balanceado: la suma de débitos debe ser igual a la suma de créditos",
      JOURNAL_NOT_BALANCED,
    );
  }
}

// ── I2: mínimo 2 líneas ──

export class JournalMinLines extends ValidationError {
  constructor() {
    super(
      "El asiento debe tener al menos dos líneas",
      MINIMUM_TWO_LINES_REQUIRED,
    );
  }
}

// ── I10: una línea — sin both-sides + sin zero ──

export class JournalLineZeroAmount extends ValidationError {
  constructor() {
    super(
      "El monto de la línea debe ser mayor que cero",
      JOURNAL_LINE_ZERO_AMOUNT,
    );
  }
}

export class JournalLineBothSides extends ValidationError {
  constructor() {
    super(
      "Una línea no puede tener débito y crédito al mismo tiempo",
      JOURNAL_LINE_BOTH_SIDES,
    );
  }
}

// ── I5: status transitions ──

export class InvalidJournalStatus extends ValidationError {
  constructor(value: string) {
    super(`Estado de asiento inválido: ${value}`, INVALID_JOURNAL_STATUS);
  }
}

export class InvalidJournalStatusTransition extends ValidationError {
  constructor(from: string, to: string) {
    super(
      `La transición de estado de asiento de ${from} a ${to} no está permitida`,
      INVALID_STATUS_TRANSITION,
    );
  }
}

// ── I7: VOIDED inmutable (terminal). C2-FIX-2 parity: every transition out of
//        VOIDED surfaces ENTRY_VOIDED_IMMUTABLE, mirroring legacy
//        validateTransition's first branch.

export class CannotModifyVoidedJournal extends ValidationError {
  constructor() {
    super(
      "Un documento anulado no puede ser modificado",
      ENTRY_VOIDED_IMMUTABLE,
    );
  }
}

// ── I9: auto-generated (sourceType !== null) inmutable vía la API contable.

export class JournalAutoGeneratedImmutable extends ValidationError {
  constructor() {
    super(
      "Los asientos generados por el sistema no pueden ser modificados desde la API contable",
      ENTRY_SYSTEM_GENERATED_IMMUTABLE,
    );
  }
}

// ── I9 variante "auto-entry void": un asiento auto-generado (sourceType !==
//        null) NO puede transitionarse a VOIDED desde la API contable. El
//        legacy emite un código DISTINTO al I9 genérico (parity
//        `journal.service.ts:563-568`) — `AUTO_ENTRY_VOID_FORBIDDEN` con
//        mensaje específico que orienta al usuario hacia el documento de
//        origen. Use-case-only: el aggregate `transitionTo` NO consulta
//        sourceType, así que auto-entries pueden post/lock/void libre vía
//        aggregate; el guard vive únicamente en el use case
//        (`JournalsService.transitionStatus`).

export class JournalAutoEntryVoidForbidden extends ValidationError {
  constructor() {
    super(
      "Este asiento fue generado automáticamente. Para anularlo, anulá el documento de origen (Venta, Compra, Despacho o Pago).",
      AUTO_ENTRY_VOID_FORBIDDEN,
    );
  }
}

// ── I6: período fiscal CLOSED — bloquea creación / contabilización / edición
//        de manual entries.

export class JournalFiscalPeriodClosed extends ValidationError {
  constructor() {
    super(
      "No se pueden crear asientos en un período cerrado",
      FISCAL_PERIOD_CLOSED,
    );
  }
}

// I12: la fecha del asiento DEBE caer dentro del rango [startDate, endDate] del
//      período fiscal asociado. Hasta hoy el use-case validaba que el período
//      estuviese OPEN (I6) pero no exigía coherencia date∈período — un POST
//      directo al API podía crear `{date: 2026-04-28, periodId: may-2026-open}`
//      sin que nada lo rechazase, dejando data inconsistente. El FE auto-deriva
//      periodId de la fecha desde el form, este invariante cierra el gap a nivel
//      backend para cualquier consumer (API directo, scripts, integraciones).
export class JournalDateOutsidePeriod extends ValidationError {
  constructor(date: Date, periodName: string) {
    super(
      `La fecha del asiento (${date.toISOString().slice(0, 10)}) está fuera del período ${periodName}`,
      JOURNAL_DATE_OUTSIDE_PERIOD,
    );
  }
}

// ── I3: account postable — la cuenta debe ser de detalle (isDetail: true).
//        El check de isActive comparte el invariante I3 desde la perspectiva
//        del aggregate "cuenta usable", pero el legacy emite código distinto
//        para inactive vs no-detail; por parity se mantienen separados.

export class JournalAccountNotPostable extends ValidationError {
  constructor() {
    super(
      "La cuenta no es de detalle (no acepta movimientos)",
      ACCOUNT_NOT_POSTABLE,
    );
  }
}

// I3 (parte 2): account isActive — emitido por el legacy SIN code (parity
// exacta con `journal.service.ts:159`). C4 shim queda thin pass-through si
// emitimos `code === undefined` igual que el legacy. Si el consumer empieza
// a distinguir, se evalúa drift en POC futuro. Anotado en bookmark de cierre
// C2 como primer caso del contador "errores legacy sin code" (umbral 3 para
// reabrir discusión).

export class JournalAccountInactive extends ValidationError {
  constructor(accountName: string) {
    super(`La cuenta "${accountName}" está desactivada`);
  }
}

// ── I4: requiresContact — si la cuenta marca requiresContact, la línea debe
//        incluir contactId. La validación de contact activo (sub-paso 4b) se
//        hace en el loop con `ContactsReadPort.getActiveById`.

export class JournalContactRequiredForAccount extends ValidationError {
  constructor(accountName: string) {
    super(
      `La cuenta "${accountName}" requiere un contacto en la línea`,
      CONTACT_REQUIRED_FOR_ACCOUNT,
    );
  }
}

// Re-export para que el módulo importe códigos por canal único.
export {
  JOURNAL_NOT_BALANCED,
  MINIMUM_TWO_LINES_REQUIRED,
  JOURNAL_LINE_ZERO_AMOUNT,
  JOURNAL_LINE_BOTH_SIDES,
  INVALID_STATUS_TRANSITION,
  ENTRY_VOIDED_IMMUTABLE,
  ENTRY_SYSTEM_GENERATED_IMMUTABLE,
  AUTO_ENTRY_VOID_FORBIDDEN,
  FISCAL_PERIOD_CLOSED,
  JOURNAL_DATE_OUTSIDE_PERIOD,
  ACCOUNT_NOT_POSTABLE,
  CONTACT_REQUIRED_FOR_ACCOUNT,
};
