import { describe, it, expect } from "vitest";
import { Journal } from "../journal.entity";
import { JournalLine } from "../journal-line.entity";
import { LineSide } from "../value-objects/line-side";
import { Money } from "@/modules/shared/domain/value-objects/money";
import {
  JournalMinLines,
  JournalNotBalanced,
  InvalidJournalStatusTransition,
  CannotModifyVoidedJournal,
  JournalAutoGeneratedImmutable,
} from "../errors/journal-errors";

const baseLines = [
  { accountId: "acc-1", side: LineSide.debit(Money.of(100)) },
  { accountId: "acc-2", side: LineSide.credit(Money.of(100)) },
];

const baseInput = {
  organizationId: "org-1",
  date: new Date("2026-04-15T00:00:00Z"),
  description: "Asiento manual de prueba",
  periodId: "period-1",
  voucherTypeId: "vt-1",
  createdById: "user-1",
  lines: baseLines,
};

describe("Journal aggregate root — construction & snapshot (B6)", () => {
  describe("create()", () => {
    it("retorna Journal en estado DRAFT", () => {
      const j = Journal.create(baseInput);
      expect(j.status).toBe("DRAFT");
    });

    it("asigna un UUID id", () => {
      const j = Journal.create(baseInput);
      expect(j.id).toMatch(
        /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/,
      );
    });

    it("number arranca null (lo asigna el adapter en C3)", () => {
      const j = Journal.create(baseInput);
      expect(j.number).toBeNull();
    });

    it("preserva campos requeridos", () => {
      const j = Journal.create(baseInput);
      expect(j.organizationId).toBe("org-1");
      expect(j.description).toBe("Asiento manual de prueba");
      expect(j.periodId).toBe("period-1");
      expect(j.voucherTypeId).toBe("vt-1");
      expect(j.createdById).toBe("user-1");
      expect(j.date.getTime()).toBe(baseInput.date.getTime());
    });

    it("optional fields default a null", () => {
      const j = Journal.create(baseInput);
      expect(j.referenceNumber).toBeNull();
      expect(j.contactId).toBeNull();
      expect(j.sourceType).toBeNull();
      expect(j.sourceId).toBeNull();
      expect(j.aiOriginalText).toBeNull();
      expect(j.updatedById).toBeNull();
    });

    it("propaga optional fields cuando se proveen", () => {
      const j = Journal.create({
        ...baseInput,
        referenceNumber: 42,
        contactId: "contact-1",
        sourceType: "sale",
        sourceId: "sale-1",
        aiOriginalText: "compra de 5 bolsas",
      });
      expect(j.referenceNumber).toBe(42);
      expect(j.contactId).toBe("contact-1");
      expect(j.sourceType).toBe("sale");
      expect(j.sourceId).toBe("sale-1");
      expect(j.aiOriginalText).toBe("compra de 5 bolsas");
    });

    it("createdAt y updatedAt son iguales al crear", () => {
      const j = Journal.create(baseInput);
      expect(j.createdAt.getTime()).toBe(j.updatedAt.getTime());
    });

    it("acepta exactamente 2 líneas (mínimo válido — partida doble axiomática)", () => {
      const j = Journal.create({
        ...baseInput,
        lines: [
          { accountId: "acc-1", side: LineSide.debit(Money.of(100)) },
          { accountId: "acc-2", side: LineSide.credit(Money.of(100)) },
        ],
      });
      expect(j.lines.length).toBe(2);
    });

    it("acepta líneas y les asigna order incremental + journalEntryId del journal", () => {
      const j = Journal.create({
        ...baseInput,
        lines: [
          { accountId: "acc-1", side: LineSide.debit(Money.of(100)) },
          { accountId: "acc-2", side: LineSide.credit(Money.of(50)) },
          { accountId: "acc-3", side: LineSide.credit(Money.of(50)) },
        ],
      });
      expect(j.lines.length).toBe(3);
      expect(j.lines[0].order).toBe(0);
      expect(j.lines[1].order).toBe(1);
      expect(j.lines[2].order).toBe(2);
      expect(j.lines[0].journalEntryId).toBe(j.id);
      expect(j.lines[1].journalEntryId).toBe(j.id);
      expect(j.lines[2].journalEntryId).toBe(j.id);
    });

    it("propaga description y contactId de cada draft a sus líneas", () => {
      const j = Journal.create({
        ...baseInput,
        lines: [
          {
            accountId: "acc-1",
            side: LineSide.debit(Money.of(100)),
            description: "Detalle 1",
            contactId: "contact-1",
          },
          { accountId: "acc-2", side: LineSide.credit(Money.of(100)) },
        ],
      });
      expect(j.lines[0].description).toBe("Detalle 1");
      expect(j.lines[0].contactId).toBe("contact-1");
      expect(j.lines[1].description).toBeNull();
      expect(j.lines[1].contactId).toBeNull();
    });
  });

  describe("I2 — mínimo 2 líneas en create() (parity legacy createEntry)", () => {
    // Failure mode declarado: JournalMinLines (validation,
    // MINIMUM_TWO_LINES_REQUIRED). Parity con legacy `journal.service.ts:127`.
    // Razón axiomática: partida doble exige ≥ 2 líneas — un Journal con 1
    // línea no representa nada contable. NO es estado intermedio legítimo.
    it("rechaza 0 líneas con JournalMinLines", () => {
      expect(() => Journal.create({ ...baseInput, lines: [] })).toThrow(
        JournalMinLines,
      );
    });

    // Failure mode declarado: JournalMinLines.
    it("rechaza 1 línea con JournalMinLines", () => {
      expect(() =>
        Journal.create({
          ...baseInput,
          lines: [{ accountId: "acc-1", side: LineSide.debit(Money.of(100)) }],
        }),
      ).toThrow(JournalMinLines);
    });

    // Failure mode declarado: JournalMinLines — ausencia de la prop `lines`
    // debe tratarse como 0 líneas, no como "skip validation".
    it("rechaza ausencia de la prop lines con JournalMinLines", () => {
      const { lines: _omit, ...inputSinLines } = baseInput;
      void _omit;
      expect(() =>
        Journal.create(inputSinLines as typeof baseInput),
      ).toThrow(JournalMinLines);
    });
  });

  describe("fromPersistence()", () => {
    it("hidrata sin re-validar — admite cualquier status y cualquier nº de líneas", () => {
      // fromPersistence no valida I2: si la DB tuviera un entry con 1 línea
      // (caso degenerado), igual se hidrata. La validación es responsabilidad
      // del factory create(), no del rehidrator.
      const line = JournalLine.fromPersistence({
        id: "line-1",
        journalEntryId: "je-x",
        accountId: "acc-1",
        side: LineSide.debit(Money.of(500)),
        description: null,
        contactId: null,
        order: 0,
      });
      const j = Journal.fromPersistence({
        id: "je-x",
        organizationId: "org-1",
        status: "POSTED",
        number: 7,
        referenceNumber: null,
        date: new Date("2026-04-15"),
        description: "x",
        periodId: "period-1",
        voucherTypeId: "vt-1",
        contactId: null,
        sourceType: null,
        sourceId: null,
        aiOriginalText: null,
        createdById: "user-1",
        updatedById: "user-2",
        createdAt: new Date("2026-04-01"),
        updatedAt: new Date("2026-04-15"),
        lines: [line],
      });
      expect(j.id).toBe("je-x");
      expect(j.status).toBe("POSTED");
      expect(j.number).toBe(7);
      expect(j.updatedById).toBe("user-2");
      expect(j.lines.length).toBe(1);
      expect(j.lines[0].id).toBe("line-1");
    });
  });

  describe("getters retornan copia defensiva del array de líneas", () => {
    it("mutar el array devuelto no muta el aggregate", () => {
      const j = Journal.create(baseInput);
      const lines = j.lines;
      lines.pop();
      expect(j.lines.length).toBe(2);
    });
  });

  describe("post() — I1 + I5 (B7)", () => {
    const balancedInput = {
      ...baseInput,
      lines: [
        { accountId: "acc-1", side: LineSide.debit(Money.of(100)) },
        { accountId: "acc-2", side: LineSide.credit(Money.of(100)) },
      ],
    };

    it("DRAFT → POSTED retorna una nueva instancia con status POSTED", async () => {
      const j = Journal.create(balancedInput);
      await new Promise((resolve) => setTimeout(resolve, 5));
      const posted = j.post();
      expect(posted).not.toBe(j);
      expect(posted.status).toBe("POSTED");
      expect(j.status).toBe("DRAFT");
      expect(posted.updatedAt.getTime()).toBeGreaterThan(j.updatedAt.getTime());
    });

    it("acepta balance exacto bit-perfect (Money.equals)", () => {
      const j = Journal.create({
        ...baseInput,
        lines: [
          { accountId: "acc-1", side: LineSide.debit(Money.of(100)) },
          { accountId: "acc-2", side: LineSide.credit(Money.of(100)) },
        ],
      });
      const posted = j.post();
      expect(posted.status).toBe("POSTED");
    });

    it("acepta balance multi-línea: 100 = 60 + 40", () => {
      const j = Journal.create({
        ...baseInput,
        lines: [
          { accountId: "acc-1", side: LineSide.debit(Money.of(100)) },
          { accountId: "acc-2", side: LineSide.credit(Money.of(60)) },
          { accountId: "acc-3", side: LineSide.credit(Money.of(40)) },
        ],
      });
      expect(() => j.post()).not.toThrow();
    });

    // Razón de elegir Decimal: con number, 0.1 + 0.2 = 0.30000000000000004 y
    // este test rompería sin drift correction. Con Money/Decimal pasa exacto.
    it("acepta balance con sumas decimales (regresión drift): 0.1 + 0.2 = 0.3", () => {
      const j = Journal.create({
        ...baseInput,
        lines: [
          { accountId: "acc-1", side: LineSide.debit(Money.of("0.1")) },
          { accountId: "acc-2", side: LineSide.debit(Money.of("0.2")) },
          { accountId: "acc-3", side: LineSide.credit(Money.of("0.3")) },
        ],
      });
      expect(() => j.post()).not.toThrow();
    });

    // Failure mode declarado: JournalNotBalanced (validation,
    // JOURNAL_NOT_BALANCED). Parity legacy `journal.service.ts:271`.
    it("rechaza desbalance simple con JournalNotBalanced", () => {
      const j = Journal.create({
        ...baseInput,
        lines: [
          { accountId: "acc-1", side: LineSide.debit(Money.of(100)) },
          { accountId: "acc-2", side: LineSide.credit(Money.of(50)) },
        ],
      });
      expect(() => j.post()).toThrow(JournalNotBalanced);
    });

    // Failure mode declarado: JournalNotBalanced — desbalance mínimo (1 centavo).
    it("rechaza desbalance de 0.01 con JournalNotBalanced", () => {
      const j = Journal.create({
        ...baseInput,
        lines: [
          { accountId: "acc-1", side: LineSide.debit(Money.of("100.00")) },
          { accountId: "acc-2", side: LineSide.credit(Money.of("99.99")) },
        ],
      });
      expect(() => j.post()).toThrow(JournalNotBalanced);
    });

    // Failure mode declarado: InvalidJournalStatusTransition (validation,
    // INVALID_STATUS_TRANSITION). I5: POSTED→POSTED no permitido.
    it("POSTED → POSTED tira InvalidJournalStatusTransition", () => {
      const j = Journal.create(balancedInput).post();
      expect(() => j.post()).toThrow(InvalidJournalStatusTransition);
    });

    // Failure mode declarado: CannotModifyVoidedJournal (validation,
    // ENTRY_VOIDED_IMMUTABLE). C2-FIX-2 parity: VOIDED es terminal — toda
    // transición fuera de VOIDED debe surface el código compartido
    // ENTRY_VOIDED_IMMUTABLE, NO el genérico INVALID_STATUS_TRANSITION.
    it("VOIDED → POSTED tira CannotModifyVoidedJournal (parity C2-FIX-2)", () => {
      const j = Journal.fromPersistence({
        id: "je-x",
        organizationId: "org-1",
        status: "VOIDED",
        number: 1,
        referenceNumber: null,
        date: new Date(),
        description: "x",
        periodId: "period-1",
        voucherTypeId: "vt-1",
        contactId: null,
        sourceType: null,
        sourceId: null,
        aiOriginalText: null,
        createdById: "user-1",
        updatedById: null,
        createdAt: new Date(),
        updatedAt: new Date(),
        lines: [],
      });
      expect(() => j.post()).toThrow(CannotModifyVoidedJournal);
    });

    // Failure mode declarado: InvalidJournalStatusTransition.
    it("LOCKED → POSTED tira InvalidJournalStatusTransition", () => {
      const j = Journal.fromPersistence({
        id: "je-x",
        organizationId: "org-1",
        status: "LOCKED",
        number: 1,
        referenceNumber: null,
        date: new Date(),
        description: "x",
        periodId: "period-1",
        voucherTypeId: "vt-1",
        contactId: null,
        sourceType: null,
        sourceId: null,
        aiOriginalText: null,
        createdById: "user-1",
        updatedById: null,
        createdAt: new Date(),
        updatedAt: new Date(),
        lines: [],
      });
      expect(() => j.post()).toThrow(InvalidJournalStatusTransition);
    });
  });

  describe("lock() — I5 + I7 (B8)", () => {
    const balancedInput = {
      ...baseInput,
      lines: [
        { accountId: "acc-1", side: LineSide.debit(Money.of(100)) },
        { accountId: "acc-2", side: LineSide.credit(Money.of(100)) },
      ],
    };

    it("POSTED → LOCKED retorna nueva instancia con status LOCKED", () => {
      const j = Journal.create(balancedInput).post();
      const locked = j.lock();
      expect(locked).not.toBe(j);
      expect(locked.status).toBe("LOCKED");
    });

    // Failure mode declarado: InvalidJournalStatusTransition.
    it("DRAFT → LOCKED tira InvalidJournalStatusTransition", () => {
      const j = Journal.create(balancedInput);
      expect(() => j.lock()).toThrow(InvalidJournalStatusTransition);
    });

    // Failure mode declarado: InvalidJournalStatusTransition.
    it("LOCKED → LOCKED tira InvalidJournalStatusTransition", () => {
      const j = Journal.create(balancedInput).post().lock();
      expect(() => j.lock()).toThrow(InvalidJournalStatusTransition);
    });

    // Failure mode declarado: CannotModifyVoidedJournal (parity C2-FIX-2).
    it("VOIDED → LOCKED tira CannotModifyVoidedJournal", () => {
      const j = Journal.create(balancedInput).post().void();
      expect(() => j.lock()).toThrow(CannotModifyVoidedJournal);
    });
  });

  describe("void() — I5 + I7 (B8)", () => {
    const balancedInput = {
      ...baseInput,
      lines: [
        { accountId: "acc-1", side: LineSide.debit(Money.of(100)) },
        { accountId: "acc-2", side: LineSide.credit(Money.of(100)) },
      ],
    };

    it("POSTED → VOIDED retorna nueva instancia con status VOIDED", () => {
      const j = Journal.create(balancedInput).post();
      const voided = j.void();
      expect(voided).not.toBe(j);
      expect(voided.status).toBe("VOIDED");
    });

    it("LOCKED → VOIDED es transición permitida (cierre admin con justificación)", () => {
      const j = Journal.create(balancedInput).post().lock();
      const voided = j.void();
      expect(voided.status).toBe("VOIDED");
    });

    // Failure mode declarado: InvalidJournalStatusTransition.
    it("DRAFT → VOIDED tira InvalidJournalStatusTransition", () => {
      const j = Journal.create(balancedInput);
      expect(() => j.void()).toThrow(InvalidJournalStatusTransition);
    });

    // Failure mode declarado: CannotModifyVoidedJournal (parity C2-FIX-2).
    // VOIDED → VOIDED, como toda transición fuera de VOIDED, surface el
    // código compartido ENTRY_VOIDED_IMMUTABLE — NO el genérico
    // INVALID_STATUS_TRANSITION.
    it("VOIDED → VOIDED tira CannotModifyVoidedJournal (terminal)", () => {
      const j = Journal.create(balancedInput).post().void();
      expect(() => j.void()).toThrow(CannotModifyVoidedJournal);
    });
  });

  describe("update() — I7 + I9 (B9)", () => {
    it("actualiza description en DRAFT", () => {
      const j = Journal.create(baseInput);
      const updated = j.update({ description: "Nueva descripción" });
      expect(updated.description).toBe("Nueva descripción");
    });

    it("actualiza date", () => {
      const j = Journal.create(baseInput);
      const newDate = new Date("2026-12-31T00:00:00Z");
      const updated = j.update({ date: newDate });
      expect(updated.date.getTime()).toBe(newDate.getTime());
    });

    it("actualiza referenceNumber", () => {
      const j = Journal.create(baseInput);
      const updated = j.update({ referenceNumber: 99 });
      expect(updated.referenceNumber).toBe(99);
    });

    it("permite limpiar referenceNumber con null", () => {
      const j = Journal.create({ ...baseInput, referenceNumber: 5 });
      const updated = j.update({ referenceNumber: null });
      expect(updated.referenceNumber).toBeNull();
    });

    it("retorna nueva instancia (inmutable)", () => {
      const j = Journal.create(baseInput);
      const updated = j.update({ description: "z" });
      expect(updated).not.toBe(j);
      expect(j.description).toBe("Asiento manual de prueba");
    });

    it("bumps updatedAt", async () => {
      const j = Journal.create(baseInput);
      await new Promise((resolve) => setTimeout(resolve, 5));
      const updated = j.update({ description: "z" });
      expect(updated.updatedAt.getTime()).toBeGreaterThan(j.updatedAt.getTime());
    });

    it("registra updatedById cuando se provee", () => {
      const j = Journal.create(baseInput);
      const updated = j.update({ updatedById: "user-2" });
      expect(updated.updatedById).toBe("user-2");
    });

    it("permite update en POSTED (caso manual orquestado por use case)", () => {
      const j = Journal.create({
        ...baseInput,
        lines: [
          { accountId: "acc-1", side: LineSide.debit(Money.of(100)) },
          { accountId: "acc-2", side: LineSide.credit(Money.of(100)) },
        ],
      }).post();
      const updated = j.update({ description: "editado en posted" });
      expect(updated.description).toBe("editado en posted");
    });

    it("permite update en LOCKED (use case verifica I8)", () => {
      const j = Journal.create({
        ...baseInput,
        lines: [
          { accountId: "acc-1", side: LineSide.debit(Money.of(100)) },
          { accountId: "acc-2", side: LineSide.credit(Money.of(100)) },
        ],
      })
        .post()
        .lock();
      const updated = j.update({ description: "editado locked" });
      expect(updated.description).toBe("editado locked");
    });

    // Failure mode declarado: CannotModifyVoidedJournal (validation,
    // ENTRY_VOIDED_IMMUTABLE). I7 — parity legacy l324-328.
    it("rechaza update en VOIDED con CannotModifyVoidedJournal", () => {
      const j = Journal.create({
        ...baseInput,
        lines: [
          { accountId: "acc-1", side: LineSide.debit(Money.of(100)) },
          { accountId: "acc-2", side: LineSide.credit(Money.of(100)) },
        ],
      })
        .post()
        .void();
      expect(() => j.update({ description: "x" })).toThrow(
        CannotModifyVoidedJournal,
      );
    });

    // Failure mode declarado: JournalAutoGeneratedImmutable (validation,
    // ENTRY_SYSTEM_GENERATED_IMMUTABLE). I9 — más estricto que legacy
    // (legacy solo aplica en POSTED; el aggregate aplica en cualquier status
    // por safety, ver comentario en assertMutable).
    it("rechaza update en auto-generated con JournalAutoGeneratedImmutable", () => {
      const j = Journal.create({
        ...baseInput,
        sourceType: "sale",
        sourceId: "sale-1",
      });
      expect(() => j.update({ description: "x" })).toThrow(
        JournalAutoGeneratedImmutable,
      );
    });

    // Failure mode declarado: JournalAutoGeneratedImmutable. Caso "ai".
    it("rechaza update en auto-generated tipo 'ai'", () => {
      const j = Journal.create({
        ...baseInput,
        sourceType: "ai",
        aiOriginalText: "compra de bolsas",
      });
      expect(() => j.update({ description: "x" })).toThrow(
        JournalAutoGeneratedImmutable,
      );
    });
  });

  describe("replaceLines() — I7 + I9 + I2 (B9)", () => {
    const validDrafts = [
      { accountId: "acc-1", side: LineSide.debit(Money.of(200)) },
      { accountId: "acc-2", side: LineSide.credit(Money.of(200)) },
    ];

    it("reemplaza la lista de líneas en DRAFT", () => {
      const j = Journal.create(baseInput);
      const updated = j.replaceLines(validDrafts);
      expect(updated.lines.length).toBe(2);
      expect(updated.lines[0].accountId).toBe("acc-1");
      expect(updated.lines[1].accountId).toBe("acc-2");
    });

    it("re-asigna order incremental y journalEntryId del aggregate", () => {
      const j = Journal.create(baseInput);
      const updated = j.replaceLines([
        { accountId: "acc-a", side: LineSide.debit(Money.of(50)) },
        { accountId: "acc-b", side: LineSide.credit(Money.of(50)) },
        { accountId: "acc-c", side: LineSide.debit(Money.of(0.01)) },
        { accountId: "acc-d", side: LineSide.credit(Money.of(0.01)) },
      ]);
      expect(updated.lines.map((l) => l.order)).toEqual([0, 1, 2, 3]);
      updated.lines.forEach((l) => expect(l.journalEntryId).toBe(j.id));
    });

    it("preserva header (description, date, status, número)", () => {
      const j = Journal.create(baseInput);
      const updated = j.replaceLines(validDrafts);
      expect(updated.description).toBe(j.description);
      expect(updated.status).toBe(j.status);
      expect(updated.date.getTime()).toBe(j.date.getTime());
      expect(updated.number).toBe(j.number);
    });

    it("retorna nueva instancia y bumps updatedAt", async () => {
      const j = Journal.create(baseInput);
      await new Promise((resolve) => setTimeout(resolve, 5));
      const updated = j.replaceLines(validDrafts);
      expect(updated).not.toBe(j);
      expect(updated.updatedAt.getTime()).toBeGreaterThan(j.updatedAt.getTime());
    });

    // Failure mode declarado: JournalMinLines.
    it("rechaza 0 líneas con JournalMinLines", () => {
      const j = Journal.create(baseInput);
      expect(() => j.replaceLines([])).toThrow(JournalMinLines);
    });

    // Failure mode declarado: JournalMinLines.
    it("rechaza 1 línea con JournalMinLines", () => {
      const j = Journal.create(baseInput);
      expect(() =>
        j.replaceLines([
          { accountId: "acc-1", side: LineSide.debit(Money.of(100)) },
        ]),
      ).toThrow(JournalMinLines);
    });

    // Failure mode declarado: CannotModifyVoidedJournal. I7.
    it("rechaza replaceLines en VOIDED con CannotModifyVoidedJournal", () => {
      const j = Journal.create(baseInput).post().void();
      expect(() => j.replaceLines(validDrafts)).toThrow(
        CannotModifyVoidedJournal,
      );
    });

    // Failure mode declarado: JournalAutoGeneratedImmutable. I9.
    it("rechaza replaceLines en auto-generated con JournalAutoGeneratedImmutable", () => {
      const j = Journal.create({
        ...baseInput,
        sourceType: "sale",
        sourceId: "sale-1",
      });
      expect(() => j.replaceLines(validDrafts)).toThrow(
        JournalAutoGeneratedImmutable,
      );
    });

    // I1 — partida doble enforzada por replaceLines SOLO en POSTED. Parity
    // legacy `journal.service.ts:352-358` chequeaba balance dentro de la
    // rama POSTED del use case; C2-D-b baja la regla al entity (R9 / §5.5).
    // Failure mode declarado: JournalNotBalanced.
    it("rechaza replaceLines en POSTED con drafts desbalanceados con JournalNotBalanced", () => {
      const j = Journal.create(baseInput).post();
      expect(() =>
        j.replaceLines([
          { accountId: "acc-1", side: LineSide.debit(Money.of(100)) },
          { accountId: "acc-2", side: LineSide.credit(Money.of(50)) },
        ]),
      ).toThrow(JournalNotBalanced);
    });

    // I1 regression — DRAFT NO re-balancea en replaceLines (parity legacy).
    // Razón: `Journal.create` admite drafts no-balanceados temporalmente y
    // los use cases createEntry / createAndPost dependen de poder armar el
    // aggregate desbalanceado para chequearlo después. Endurecer aquí
    // rompe createEntry. Failure mode declarado: NO throws.
    it("permite replaceLines en DRAFT con drafts desbalanceados (parity)", () => {
      const j = Journal.create(baseInput);
      expect(() =>
        j.replaceLines([
          { accountId: "acc-1", side: LineSide.debit(Money.of(100)) },
          { accountId: "acc-2", side: LineSide.credit(Money.of(50)) },
        ]),
      ).not.toThrow();
    });

    // I1 regression — LOCKED NO re-balancea en replaceLines (parity legacy).
    // Razón: el aggregate ya pasó por `transitionTo("POSTED")` que validó
    // partida doble; LOCKED es un estado posterior y la regla no se
    // re-evalúa salvo en una nueva transición a POSTED. Failure mode
    // declarado: NO throws.
    it("permite replaceLines en LOCKED con drafts desbalanceados (parity)", () => {
      const j = Journal.create(baseInput).post().lock();
      expect(() =>
        j.replaceLines([
          { accountId: "acc-1", side: LineSide.debit(Money.of(100)) },
          { accountId: "acc-2", side: LineSide.credit(Money.of(50)) },
        ]),
      ).not.toThrow();
    });
  });

  describe("toSnapshot()", () => {
    it("retorna POJO con líneas como snapshots de números", () => {
      const j = Journal.create(baseInput);
      const snap = j.toSnapshot();
      expect(snap.lines.length).toBe(2);
      expect(typeof snap.lines[0].debit).toBe("number");
      expect(typeof snap.lines[0].credit).toBe("number");
      expect(snap.lines[0].debit).toBe(100);
      expect(snap.lines[1].credit).toBe(100);
    });

    it("preserva ids, status, dates, número null inicial", () => {
      const j = Journal.create(baseInput);
      const snap = j.toSnapshot();
      expect(snap.id).toBe(j.id);
      expect(snap.organizationId).toBe("org-1");
      expect(snap.status).toBe("DRAFT");
      expect(snap.number).toBeNull();
      expect(snap.createdAt).toBeInstanceOf(Date);
      expect(snap.updatedAt).toBeInstanceOf(Date);
    });

    it("preserva sourceType/sourceId/aiOriginalText", () => {
      const j = Journal.create({
        ...baseInput,
        sourceType: "ai",
        sourceId: null,
        aiOriginalText: "compra de 5 bolsas",
      });
      const snap = j.toSnapshot();
      expect(snap.sourceType).toBe("ai");
      expect(snap.aiOriginalText).toBe("compra de 5 bolsas");
    });
  });
});

describe("regenerateFromSource() — I7 + I1 + I2 (skip I9 by design — POC #11.0a A3 Ciclo 4-pre)", () => {
  // Escape hatch nombrado γ7 §13 emergente Ciclo 4 lockeado Marco. Skip I9
  // (auto-generated inmutable) — único caller legítimo: sale-hex use case
  // `regenerateJournalForIvaChange` via `JournalEntryFactoryPort.
  // regenerateForSaleEdit`. Conserva I7 (VOIDED inmutable), I1 (balance POSTED),
  // I2 (>= 2 líneas).
  const validDrafts = [
    { accountId: "acc-1", side: LineSide.debit(Money.of(200)) },
    { accountId: "acc-2", side: LineSide.credit(Money.of(200)) },
  ];

  const updateInput = {
    description: "Edited via source regenerate",
    updatedById: "user-2",
  };

  it("muta header + reemplaza lines en auto-generated POSTED (caso real sale-edit)", () => {
    // RED honesty: pre-GREEN throws "regenerateFromSource is not a function"
    // (método inexistente). Post-GREEN: skip I9 — journal con sourceType="sale"
    // + status=POSTED se muta sin throw, header + lines actualizadas, id +
    // sourceType preservados.
    const j = Journal.create({
      ...baseInput,
      sourceType: "sale",
      sourceId: "sale-1",
    }).post();

    const updated = j.regenerateFromSource(updateInput, validDrafts);

    expect(updated.description).toBe("Edited via source regenerate");
    expect(updated.updatedById).toBe("user-2");
    expect(updated.sourceType).toBe("sale");
    expect(updated.sourceId).toBe("sale-1");
    expect(updated.lines).toHaveLength(2);
    expect(updated.lines[0].accountId).toBe("acc-1");
    expect(updated.lines[1].accountId).toBe("acc-2");
    expect(updated.status).toBe("POSTED");
    expect(updated.id).toBe(j.id);
  });

  it("retorna nueva instancia y bumps updatedAt (parity replaceLines)", async () => {
    // RED honesty: pre-GREEN throws. Post-GREEN: nuevo aggregate, updatedAt mayor.
    const j = Journal.create({
      ...baseInput,
      sourceType: "sale",
      sourceId: "sale-1",
    }).post();
    await new Promise((resolve) => setTimeout(resolve, 5));

    const updated = j.regenerateFromSource(updateInput, validDrafts);

    expect(updated).not.toBe(j);
    expect(updated.updatedAt.getTime()).toBeGreaterThan(j.updatedAt.getTime());
  });

  // Failure mode declarado: CannotModifyVoidedJournal. I7 conservado.
  it("rechaza regenerateFromSource en VOIDED con CannotModifyVoidedJournal (I7 conservado)", () => {
    // RED honesty: pre-GREEN throws "is not a function". Post-GREEN: VOIDED
    // siempre inmutable, parity update()/replaceLines(). I7 NO se relaja.
    const j = Journal.create({
      ...baseInput,
      sourceType: "sale",
      sourceId: "sale-1",
    })
      .post()
      .void();

    expect(() => j.regenerateFromSource(updateInput, validDrafts)).toThrow(
      CannotModifyVoidedJournal,
    );
  });

  // Failure mode declarado: JournalNotBalanced. I1 conservado en POSTED.
  it("rechaza drafts desbalanceados en POSTED con JournalNotBalanced (I1 conservado)", () => {
    // RED honesty: pre-GREEN throws "is not a function". Post-GREEN: parity
    // replaceLines — assertLinesBalanced solo en POSTED.
    const j = Journal.create({
      ...baseInput,
      sourceType: "sale",
      sourceId: "sale-1",
    }).post();

    expect(() =>
      j.regenerateFromSource(updateInput, [
        { accountId: "acc-1", side: LineSide.debit(Money.of(100)) },
        { accountId: "acc-2", side: LineSide.credit(Money.of(50)) },
      ]),
    ).toThrow(JournalNotBalanced);
  });

  // Failure mode declarado: JournalMinLines. I2 conservado.
  it("rechaza < 2 líneas con JournalMinLines (I2 conservado)", () => {
    // RED honesty: pre-GREEN throws "is not a function". Post-GREEN: I2 check
    // antes del balance, parity replaceLines.
    const j = Journal.create({
      ...baseInput,
      sourceType: "sale",
      sourceId: "sale-1",
    }).post();

    expect(() =>
      j.regenerateFromSource(updateInput, [
        { accountId: "acc-1", side: LineSide.debit(Money.of(100)) },
      ]),
    ).toThrow(JournalMinLines);
  });

  // Failure mode declarado: NO throws (incluyendo I9). I9 skip por diseño γ7
  // — el comportamiento DIVERGENTE explícito vs update()/replaceLines() (que
  // SÍ throw JournalAutoGeneratedImmutable cuando sourceType !== null).
  // Aserción doble (parity RED honesty): `.not.toThrow()` simple para que
  // pre-GREEN "is not a function" haga FAIL uniform; assertion sobre return
  // value confirma método materializado en GREEN.
  it("permite regenerateFromSource en auto-generated (sourceType !== null) — I9 skip por diseño γ7", () => {
    // RED honesty: pre-GREEN throws TypeError "is not a function" → .not.toThrow()
    // FALLA (uniform con los otros 5 tests). Post-GREEN: no throws + return
    // aggregate hidratado preservando sourceType. Replace lines+update con
    // sourceType="sale" throws JournalAutoGeneratedImmutable; regenerateFromSource
    // NO — escape hatch nombrado γ7 sale-edit flow.
    const j = Journal.create({
      ...baseInput,
      sourceType: "sale",
      sourceId: "sale-1",
    }).post();

    expect(() =>
      j.regenerateFromSource(updateInput, validDrafts),
    ).not.toThrow();

    const updated = j.regenerateFromSource(updateInput, validDrafts);
    expect(updated.sourceType).toBe("sale");
    expect(updated.lines).toHaveLength(2);
  });
});
