-- Drift-cleanup migration auto-generated by `prisma migrate dev` after the
-- annual_close migration applied. Two unrelated adjustments:
--   1. fiscal_years.updatedAt: drop the DEFAULT now() seeded by the hand-written
--      annual_close migration. The Prisma model uses @updatedAt — Prisma writes
--      the value on every UPDATE, no DB-side default required. (Already corrected
--      in 20260516030000_annual_close/migration.sql for fresh DBs; this catches
--      any environment that applied the older version.)
--   2. org_settings defaults: belated update to match a prior chart-of-accounts
--      change (1.1.3.1 banco / 5.1.9 flete). Pre-existing drift, not annual-close.
--
-- AlterTable
ALTER TABLE "fiscal_years" ALTER COLUMN "updatedAt" DROP DEFAULT;

-- AlterTable
ALTER TABLE "org_settings" ALTER COLUMN "bancoAccountCode" SET DEFAULT '1.1.3.1',
ALTER COLUMN "fleteExpenseAccountCode" SET DEFAULT '5.1.9';
