-- ============================================================
-- DOWN migration for 20260516030000_annual_close (MANUAL — not auto-applied)
-- ============================================================
--
-- Prisma does not run DOWN scripts automatically. This file is a documented
-- rollback artefact: an operator/DBA may apply it manually to revert the
-- annual_close schema change in a controlled environment.
--
-- WHAT IT REVERTS:
--   - audit_fiscal_years trigger (the shared audit_trigger_fn is NOT dropped
--     because other tables still rely on it).
--   - FK + index + NOT NULL constraint on fiscal_periods.fiscalYearId, then
--     the column itself.
--   - fiscal_years table (CASCADE removes its 4 FK constraints + 4 indexes
--     + audit trigger if step 1 was somehow skipped).
--   - FiscalYearStatus enum.
--
-- WHAT IT DOES NOT REVERT:
--   - The CC voucher type (`code='CC'`) seeded by
--     prisma/seeds/voucher-types.ts. CC is a data-migration, not a schema
--     change; removing the seed entry is a separate prisma/seeds/ edit
--     paired with a per-org delete:
--       DELETE FROM voucher_types WHERE code='CC';
--   - audit_logs rows generated by AFTER UPDATE/DELETE on fiscal_years
--     during the period the schema was live (intentionally retained for
--     forensics).
--   - Historical fiscal_periods rows. fiscalYearId reverts to non-existent,
--     so the only data loss is the (orgId, year) → fiscalYearId
--     correlation, which can be recomputed from (organizationId, year).
--
-- PRE-CONDITIONS:
--   - No application code MUST be querying prisma.fiscalYear at the time
--     of rollback (it will error after schema revert).
--   - schema.prisma MUST be reverted to a state without FiscalYear /
--     FiscalYearStatus / FiscalPeriod.fiscalYearId BEFORE the next
--     `prisma generate` runs.
--
-- USAGE:
--   psql "$DATABASE_URL" -f prisma/migrations/20260516030000_annual_close/down.sql
--   # then revert schema.prisma + `prisma migrate resolve --rolled-back 20260516030000_annual_close`
-- ============================================================

BEGIN;

-- 1) Drop audit trigger on fiscal_years (function audit_trigger_fn is shared
--    with other tables and must NOT be dropped here).
DROP TRIGGER IF EXISTS audit_fiscal_years ON "fiscal_years";

-- 2) Drop FK, NOT NULL constraint, index, and column on fiscal_periods.
DROP INDEX  IF EXISTS "fiscal_periods_fiscalYearId_idx";
ALTER TABLE "fiscal_periods" DROP CONSTRAINT IF EXISTS "fiscal_periods_fiscalYearId_fkey";
ALTER TABLE "fiscal_periods" ALTER COLUMN "fiscalYearId" DROP NOT NULL;
ALTER TABLE "fiscal_periods" DROP COLUMN IF EXISTS "fiscalYearId";

-- 3) Drop fiscal_years table (CASCADE handles dependent FK + indexes + any
--    leftover triggers from step 1 being skipped).
DROP TABLE IF EXISTS "fiscal_years" CASCADE;

-- 4) Drop the enum last (table must be gone first).
DROP TYPE IF EXISTS "FiscalYearStatus";

COMMIT;
