import { Money } from "@/modules/shared/domain/value-objects/money";
import {
  JournalEntryStatus,
  canTransition,
} from "./value-objects/journal-entry-status";
import { LineSide } from "./value-objects/line-side";
import {
  JournalLine,
  type JournalLineSnapshot,
} from "./journal-line.entity";
import {
  JournalMinLines,
  JournalNotBalanced,
  InvalidJournalStatusTransition,
  CannotModifyVoidedJournal,
  JournalAutoGeneratedImmutable,
} from "./errors/journal-errors";

export interface JournalProps {
  id: string;
  organizationId: string;
  status: JournalEntryStatus;
  // `number` is the auto-generated sequential voucher number. The Prisma adapter
  // (C3) assigns it during insert via retry loop (VOUCHER_NUMBER_CONTENTION);
  // pre-persistence the field is null. This is analogous to Payment.journalEntryId.
  number: number | null;
  referenceNumber: number | null;
  date: Date;
  description: string;
  periodId: string;
  voucherTypeId: string;
  contactId: string | null;
  // `sourceType` distinguishes manual (null) from auto-generated entries
  // (sale/purchase/payment/ai). I9 forbids mutators when sourceType !== null.
  sourceType: string | null;
  sourceId: string | null;
  aiOriginalText: string | null;
  createdById: string;
  updatedById: string | null;
  createdAt: Date;
  updatedAt: Date;
  lines: JournalLine[];
}

export interface JournalLineDraft {
  accountId: string;
  side: LineSide;
  description?: string | null;
  contactId?: string | null;
}

export interface UpdateJournalInput {
  description?: string;
  date?: Date;
  referenceNumber?: number | null;
  contactId?: string | null;
  updatedById?: string;
  // `sourceType`/`sourceId`/`aiOriginalText` son inmutables post-creación
  // (I9). No se exponen en el input de update.
  // Las líneas se reemplazan por `replaceLines()`, no por `update()`.
}

export interface CreateJournalInput {
  organizationId: string;
  date: Date;
  description: string;
  periodId: string;
  voucherTypeId: string;
  createdById: string;
  contactId?: string | null;
  referenceNumber?: number | null;
  sourceType?: string | null;
  sourceId?: string | null;
  aiOriginalText?: string | null;
  lines?: JournalLineDraft[];
}

export interface JournalSnapshot {
  id: string;
  organizationId: string;
  status: JournalEntryStatus;
  number: number | null;
  referenceNumber: number | null;
  date: Date;
  description: string;
  periodId: string;
  voucherTypeId: string;
  contactId: string | null;
  sourceType: string | null;
  sourceId: string | null;
  aiOriginalText: string | null;
  createdById: string;
  updatedById: string | null;
  createdAt: Date;
  updatedAt: Date;
  lines: JournalLineSnapshot[];
}

/**
 * Journal is the aggregate root that owns the JournalLine child entities. It
 * enforces the journal-intrinsic invariants (I1, I2, I5, I7, I9, I10). The
 * collaboration-required invariants (I3 account postable, I4 requiresContact,
 * I6 period OPEN, I8 LOCKED requires role+justification) live in the use case
 * layer (C2), where repositories and the role context are available.
 *
 * In this block (B6) only construction, hydration, getters and snapshot are
 * implemented — transitions and balance checks come in B7-B9.
 */
export class Journal {
  private constructor(private readonly props: JournalProps) {}

  static create(input: CreateJournalInput): Journal {
    // I2 — mínimo 2 líneas. Parity con legacy `journal.service.ts:127`.
    // Razón axiomática: partida doble exige >= 2 líneas; un Journal con 0/1
    // línea no representa nada contable. Se chequea en construcción, no en
    // post(), para mantener el shim de C4 como pass-through fino y evitar
    // duplicación de validación (problema limpiado en commit a67dfc9).
    const drafts = input.lines ?? [];
    if (drafts.length < 2) {
      throw new JournalMinLines();
    }

    const id = crypto.randomUUID();
    const now = new Date();

    const lines = drafts.map((draft, index) =>
      JournalLine.create({
        journalEntryId: id,
        accountId: draft.accountId,
        side: draft.side,
        description: draft.description ?? null,
        contactId: draft.contactId ?? null,
        order: index,
      }),
    );

    return new Journal({
      id,
      organizationId: input.organizationId,
      status: "DRAFT",
      number: null,
      referenceNumber: input.referenceNumber ?? null,
      date: input.date,
      description: input.description,
      periodId: input.periodId,
      voucherTypeId: input.voucherTypeId,
      contactId: input.contactId ?? null,
      sourceType: input.sourceType ?? null,
      sourceId: input.sourceId ?? null,
      aiOriginalText: input.aiOriginalText ?? null,
      createdById: input.createdById,
      updatedById: null,
      createdAt: now,
      updatedAt: now,
      lines,
    });
  }

  static fromPersistence(props: JournalProps): Journal {
    return new Journal(props);
  }

  // ── Getters ──

  get id(): string {
    return this.props.id;
  }
  get organizationId(): string {
    return this.props.organizationId;
  }
  get status(): JournalEntryStatus {
    return this.props.status;
  }
  get number(): number | null {
    return this.props.number;
  }
  get referenceNumber(): number | null {
    return this.props.referenceNumber;
  }
  get date(): Date {
    return this.props.date;
  }
  get description(): string {
    return this.props.description;
  }
  get periodId(): string {
    return this.props.periodId;
  }
  get voucherTypeId(): string {
    return this.props.voucherTypeId;
  }
  get contactId(): string | null {
    return this.props.contactId;
  }
  get sourceType(): string | null {
    return this.props.sourceType;
  }
  get sourceId(): string | null {
    return this.props.sourceId;
  }
  get aiOriginalText(): string | null {
    return this.props.aiOriginalText;
  }
  get createdById(): string {
    return this.props.createdById;
  }
  get updatedById(): string | null {
    return this.props.updatedById;
  }
  get createdAt(): Date {
    return this.props.createdAt;
  }
  get updatedAt(): Date {
    return this.props.updatedAt;
  }
  get lines(): JournalLine[] {
    return [...this.props.lines];
  }

  // ── Status transitions (B7+) ──

  post(): Journal {
    return this.transitionTo("POSTED");
  }

  lock(): Journal {
    return this.transitionTo("LOCKED");
  }

  void(): Journal {
    return this.transitionTo("VOIDED");
  }

  // ── Mutators (B9) — I7 + I9 ──

  update(input: UpdateJournalInput): Journal {
    this.assertMutable();
    const next: JournalProps = { ...this.props, updatedAt: new Date() };
    if (input.description !== undefined) next.description = input.description;
    if (input.date !== undefined) next.date = input.date;
    if ("referenceNumber" in input) {
      next.referenceNumber = input.referenceNumber ?? null;
    }
    if ("contactId" in input) next.contactId = input.contactId ?? null;
    if (input.updatedById !== undefined) next.updatedById = input.updatedById;
    return new Journal(next);
  }

  replaceLines(drafts: JournalLineDraft[]): Journal {
    this.assertMutable();
    if (drafts.length < 2) {
      throw new JournalMinLines();
    }
    const lines = drafts.map((draft, index) =>
      JournalLine.create({
        journalEntryId: this.props.id,
        accountId: draft.accountId,
        side: draft.side,
        description: draft.description ?? null,
        contactId: draft.contactId ?? null,
        order: index,
      }),
    );
    // I1 — balance enforzado solo en POSTED. Parity legacy
    // `journal.service.ts:352-358`. DRAFT y LOCKED conservan parity (no
    // re-balancean) — el chequeo previo al pasar a POSTED garantiza la
    // partida doble en estados terminales.
    if (this.props.status === "POSTED") {
      this.assertLinesBalanced(lines);
    }
    return new Journal({
      ...this.props,
      lines,
      updatedAt: new Date(),
    });
  }

  /**
   * Mutates header + replaces lines atomically, **skipping I9** (auto-generated
   * inmutable). Named escape hatch γ7 §13 emergente Ciclo 4 lockeado Marco —
   * único caller legítimo: sale-hex use case `regenerateJournalForIvaChange`
   * via `JournalEntryFactoryPort.regenerateForSaleEdit`. Otros consumers DEBEN
   * usar `update()` + `replaceLines()` y aceptar enforcement I9.
   *
   * **Conservados**: I7 (VOIDED inmutable siempre), I1 (partida doble solo
   * POSTED, parity `replaceLines`), I2 (>= 2 líneas).
   *
   * **Skipped por diseño**: I9 (`sourceType !== null`) — la única divergencia
   * vs `update()` + `replaceLines()`. Razón: el aggregate accounting hex eligió
   * I9 "más conservador que legacy" sin considerar el flow sale-edit/regenerate
   * (POC #11.0a A2 Ciclo 6b). Este método es la reconciliación nombrada:
   * "I am the source-edit flow for this auto-entry" como statement explícito
   * del caller.
   */
  regenerateFromSource(
    input: UpdateJournalInput,
    drafts: JournalLineDraft[],
  ): Journal {
    // I7 — VOIDED siempre inmutable (parity update/replaceLines).
    if (this.props.status === "VOIDED") {
      throw new CannotModifyVoidedJournal();
    }
    // (I9 skip por diseño γ7)
    // I2 — >= 2 líneas (parity replaceLines).
    if (drafts.length < 2) {
      throw new JournalMinLines();
    }

    const next: JournalProps = { ...this.props, updatedAt: new Date() };
    if (input.description !== undefined) next.description = input.description;
    if (input.date !== undefined) next.date = input.date;
    if ("referenceNumber" in input) {
      next.referenceNumber = input.referenceNumber ?? null;
    }
    if ("contactId" in input) next.contactId = input.contactId ?? null;
    if (input.updatedById !== undefined) next.updatedById = input.updatedById;

    const lines = drafts.map((draft, index) =>
      JournalLine.create({
        journalEntryId: this.props.id,
        accountId: draft.accountId,
        side: draft.side,
        description: draft.description ?? null,
        contactId: draft.contactId ?? null,
        order: index,
      }),
    );
    // I1 — balance solo POSTED (parity replaceLines).
    if (this.props.status === "POSTED") {
      this.assertLinesBalanced(lines);
    }

    return new Journal({ ...next, lines });
  }

  private assertMutable(): void {
    // I7 — VOIDED inmutable. C2-FIX-2 parity: surface ENTRY_VOIDED_IMMUTABLE.
    if (this.props.status === "VOIDED") {
      throw new CannotModifyVoidedJournal();
    }
    // I9 — auto-generated inmutable via accounting API. Aplica en cualquier
    // status. Razón: entries derivados de upstream documents (sale/purchase/
    // payment/dispatch) son authoritative — el edit debe re-derivar desde
    // el documento upstream, no mutar el journal directamente.
    //
    // I9-AI exception (sdd/ai-journal-posted-editable): sourceType="ai" es
    // drafting helper, no auto-entry derivado. El usuario es dueño del
    // asiento desde la creación y edita DRAFT libremente. Al postear, la
    // provenance se disuelve en transitionTo("POSTED") clears sourceType +
    // aiOriginalText) — POSTED entra a I9 con sourceType=null naturalmente.
    if (this.props.sourceType !== null && this.props.sourceType !== "ai") {
      throw new JournalAutoGeneratedImmutable();
    }
  }

  private transitionTo(target: JournalEntryStatus): Journal {
    // C2-FIX-2 parity: VOIDED es terminal — toda transición fuera de VOIDED
    // surface ENTRY_VOIDED_IMMUTABLE, NO el genérico INVALID_STATUS_TRANSITION.
    if (this.props.status === "VOIDED") {
      throw new CannotModifyVoidedJournal();
    }
    if (!canTransition(this.props.status, target)) {
      throw new InvalidJournalStatusTransition(this.props.status, target);
    }
    // I1 — partida doble: chequear solo cuando target === POSTED. LOCKED y
    // VOIDED no requieren rebalance: el journal ya está balanceado por el
    // chequeo previo al llegar a POSTED.
    if (target === "POSTED") {
      this.assertBalanced();
    }
    // AI provenance dissolution: la IA es un drafting helper. Cuando el
    // usuario firma (DRAFT → POSTED), la provenance se disuelve y el asiento
    // pasa a ser fully user-owned. Limpiar sourceType + aiOriginalText permite
    // que todos los downstream layers (I9 assertMutable, VOIDED guard del
    // service, presentation guard de edit, audit classifier, badge UI) lo
    // traten como manual sin ningún cambio adicional. Aplica SOLO a "ai" —
    // sale/purchase/payment/dispatch preservan su trazabilidad al upstream.
    const isAiToPost = target === "POSTED" && this.props.sourceType === "ai";
    return new Journal({
      ...this.props,
      status: target,
      updatedAt: new Date(),
      sourceType: isAiToPost ? null : this.props.sourceType,
      aiOriginalText: isAiToPost ? null : this.props.aiOriginalText,
    });
  }

  private assertBalanced(): void {
    this.assertLinesBalanced(this.props.lines);
  }

  private assertLinesBalanced(lines: JournalLine[]): void {
    const totalDebit = lines.reduce(
      (acc, l) => acc.plus(l.side.debit ?? Money.zero()),
      Money.zero(),
    );
    const totalCredit = lines.reduce(
      (acc, l) => acc.plus(l.side.credit ?? Money.zero()),
      Money.zero(),
    );
    if (!totalDebit.equals(totalCredit)) {
      throw new JournalNotBalanced();
    }
  }

  toSnapshot(): JournalSnapshot {
    return {
      id: this.props.id,
      organizationId: this.props.organizationId,
      status: this.props.status,
      number: this.props.number,
      referenceNumber: this.props.referenceNumber,
      date: this.props.date,
      description: this.props.description,
      periodId: this.props.periodId,
      voucherTypeId: this.props.voucherTypeId,
      contactId: this.props.contactId,
      sourceType: this.props.sourceType,
      sourceId: this.props.sourceId,
      aiOriginalText: this.props.aiOriginalText,
      createdById: this.props.createdById,
      updatedById: this.props.updatedById,
      createdAt: this.props.createdAt,
      updatedAt: this.props.updatedAt,
      lines: this.props.lines.map((l) => l.toSnapshot()),
    };
  }
}
