import { afterAll, afterEach, beforeAll, describe, expect, it } from "vitest";

import { prisma } from "@/lib/prisma";
import { Journal } from "@/modules/accounting/domain/journal.entity";
import { JournalLine } from "@/modules/accounting/domain/journal-line.entity";
import { LineSide } from "@/modules/accounting/domain/value-objects/line-side";
import { Money } from "@/modules/shared/domain/value-objects/money";

import { PrismaAccountBalancesRepo } from "../prisma-account-balances.repo";

/**
 * Postgres-real integration test for PrismaAccountBalancesRepo (POC #10 C3-A).
 *
 * Pattern: same as `modules/shared/infrastructure/__tests__/
 * prisma-unit-of-work.integration.test.ts` (POC #9). Uses DATABASE_URL = dev
 * DB. Strict cleanup by orgId/periodId fixtures, never by timestamp.
 *
 * What this test exercises (the things that live in Postgres, not in TS):
 *   1. The adapter writes to `account_balances` using the injected `tx` —
 *      verifiable because if the adapter used the global `prisma` client the
 *      writes would escape the test's `prisma.$transaction` scope.
 *   2. The unique constraint `(accountId, periodId)` on `account_balances`
 *      is respected by the legacy `upsert` we delegate to (one row per
 *      account×period, no duplicates).
 *   3. Decimal precision survives the path
 *      `Money.toString() → Prisma.Decimal create → DB Decimal(12,2)`.
 *
 * Fixtures (`beforeAll`): User + Org + FiscalPeriod (year 2099, OPEN) +
 * 2 Accounts (1 ASSET DEUDORA, 1 PASIVO ACREEDORA). Minimal set for
 * test 1 — `applyVoid` test 2 reuses the same fixtures.
 *
 * The `JournalEntry` row is NOT persisted: the adapter only reads
 * `accounts` and writes `account_balances`. The `Journal` aggregate is
 * reconstructed in-memory via `Journal.fromPersistence` for each test.
 */

describe("PrismaAccountBalancesRepo — Postgres integration", () => {
  let testOrgId: string;
  let testUserId: string;
  let testPeriodId: string;
  let assetAccountId: string;
  let liabilityAccountId: string;

  beforeAll(async () => {
    const stamp = Date.now();

    const user = await prisma.user.create({
      data: {
        clerkUserId: `abr-test-clerk-user-${stamp}`,
        email: `abr-test-${stamp}@test.local`,
        name: "AccountBalancesRepo Integration Test User",
      },
    });
    testUserId = user.id;

    const org = await prisma.organization.create({
      data: {
        clerkOrgId: `abr-test-clerk-org-${stamp}`,
        name: `AccountBalancesRepo Integration Test Org ${stamp}`,
        slug: `abr-test-org-${stamp}`,
      },
    });
    testOrgId = org.id;

    const period = await prisma.fiscalPeriod.create({
      data: {
        organizationId: testOrgId,
        name: "abr-integration-period",
        year: 2099,
        month: 1,
        startDate: new Date("2099-01-01T00:00:00Z"),
        endDate: new Date("2099-01-31T23:59:59Z"),
        createdById: testUserId,
      },
    });
    testPeriodId = period.id;

    const asset = await prisma.account.create({
      data: {
        organizationId: testOrgId,
        code: "1000",
        name: "Test Asset",
        type: "ACTIVO",
        nature: "DEUDORA",
        level: 1,
        isDetail: true,
      },
    });
    assetAccountId = asset.id;

    const liability = await prisma.account.create({
      data: {
        organizationId: testOrgId,
        code: "2000",
        name: "Test Liability",
        type: "PASIVO",
        nature: "ACREEDORA",
        level: 1,
        isDetail: true,
      },
    });
    liabilityAccountId = liability.id;
  });

  afterEach(async () => {
    await prisma.accountBalance.deleteMany({
      where: { organizationId: testOrgId, periodId: testPeriodId },
    });
  });

  afterAll(async () => {
    // FK-safe order: child rows → audit_logs → org → user.
    // `audit_logs.organizationId` has FK with RESTRICT (Prisma default); rows
    // generated by triggers on INSERT into `accounts` / `organizations` etc
    // must be cleared before deleting the org. `audit_logs.changedById` is a
    // plain string (no @relation), so user.delete does NOT need pre-cleanup.
    await prisma.accountBalance.deleteMany({
      where: { organizationId: testOrgId },
    });
    await prisma.account.deleteMany({ where: { organizationId: testOrgId } });
    await prisma.fiscalPeriod.delete({ where: { id: testPeriodId } });
    await prisma.auditLog.deleteMany({
      where: { organizationId: testOrgId },
    });
    await prisma.organization.delete({ where: { id: testOrgId } });
    await prisma.user.delete({ where: { id: testUserId } });
  });

  function buildPostedJournal(): Journal {
    const journalId = crypto.randomUUID();
    const now = new Date();
    return Journal.fromPersistence({
      id: journalId,
      organizationId: testOrgId,
      status: "POSTED",
      number: 1,
      referenceNumber: null,
      date: new Date("2099-01-15T00:00:00Z"),
      description: "C3-A integration test entry",
      periodId: testPeriodId,
      voucherTypeId: "voucher-type-not-read-by-adapter",
      contactId: null,
      sourceType: null,
      sourceId: null,
      aiOriginalText: null,
      createdById: testUserId,
      updatedById: null,
      createdAt: now,
      updatedAt: now,
      lines: [
        JournalLine.fromPersistence({
          id: crypto.randomUUID(),
          journalEntryId: journalId,
          accountId: assetAccountId,
          side: LineSide.debit(Money.of("100")),
          description: null,
          contactId: null,
          order: 0,
        }),
        JournalLine.fromPersistence({
          id: crypto.randomUUID(),
          journalEntryId: journalId,
          accountId: liabilityAccountId,
          side: LineSide.credit(Money.of("100")),
          description: null,
          contactId: null,
          order: 1,
        }),
      ],
    });
  }

  it("applyPost: persists one balance row per account with debit/credit deltas matching the line amounts", async () => {
    const journal = buildPostedJournal();

    await prisma.$transaction(async (tx) => {
      const repo = new PrismaAccountBalancesRepo(tx);
      await repo.applyPost(journal);
    });

    const balances = await prisma.accountBalance.findMany({
      where: { organizationId: testOrgId, periodId: testPeriodId },
      orderBy: { account: { code: "asc" } },
    });

    expect(balances.length).toBe(2);

    expect(balances[0].accountId).toBe(assetAccountId);
    expect(balances[0].debitTotal.toString()).toBe("100");
    expect(balances[0].creditTotal.toString()).toBe("0");

    expect(balances[1].accountId).toBe(liabilityAccountId);
    expect(balances[1].debitTotal.toString()).toBe("0");
    expect(balances[1].creditTotal.toString()).toBe("100");
  });

  it("applyVoid: reverses balance increments to zero (post then void)", async () => {
    const journal = buildPostedJournal();

    await prisma.$transaction(async (tx) => {
      const repo = new PrismaAccountBalancesRepo(tx);
      await repo.applyPost(journal);
    });

    await prisma.$transaction(async (tx) => {
      const repo = new PrismaAccountBalancesRepo(tx);
      await repo.applyVoid(journal);
    });

    const balances = await prisma.accountBalance.findMany({
      where: { organizationId: testOrgId, periodId: testPeriodId },
      orderBy: { account: { code: "asc" } },
    });

    expect(balances.length).toBe(2);

    expect(balances[0].accountId).toBe(assetAccountId);
    expect(balances[0].debitTotal.toString()).toBe("0");
    expect(balances[0].creditTotal.toString()).toBe("0");

    expect(balances[1].accountId).toBe(liabilityAccountId);
    expect(balances[1].debitTotal.toString()).toBe("0");
    expect(balances[1].creditTotal.toString()).toBe("0");
  });

  function buildOffsettingJournal(amount: string): Journal {
    // Mirror of buildPostedJournal with reversed sides — asset receives
    // credit, liability receives debit. Used by the characterization test
    // to drive debitTotal AND creditTotal both non-zero per account.
    const journalId = crypto.randomUUID();
    const now = new Date();
    return Journal.fromPersistence({
      id: journalId,
      organizationId: testOrgId,
      status: "POSTED",
      number: 2,
      referenceNumber: null,
      date: new Date("2099-01-15T00:00:00Z"),
      description: "C5 P2 characterization offsetting entry",
      periodId: testPeriodId,
      voucherTypeId: "voucher-type-not-read-by-adapter",
      contactId: null,
      sourceType: null,
      sourceId: null,
      aiOriginalText: null,
      createdById: testUserId,
      updatedById: null,
      createdAt: now,
      updatedAt: now,
      lines: [
        JournalLine.fromPersistence({
          id: crypto.randomUUID(),
          journalEntryId: journalId,
          accountId: assetAccountId,
          side: LineSide.credit(Money.of(amount)),
          description: null,
          contactId: null,
          order: 0,
        }),
        JournalLine.fromPersistence({
          id: crypto.randomUUID(),
          journalEntryId: journalId,
          accountId: liabilityAccountId,
          side: LineSide.debit(Money.of(amount)),
          description: null,
          contactId: null,
          order: 1,
        }),
      ],
    });
  }

  it("applyPost: balance recomputed from nature — DEUDORA = debit - credit, ACREEDORA = credit - debit (characterization, GREEN by legacy step 3)", async () => {
    // Failure mode declarado (feedback/red-acceptance-failure-mode):
    // PASS por caracterización del paso 3 (recálculo balance por nature) ya
    // implementado en legacy `upsert` (account-balances.repository.ts:64-77).
    // NO RED genuino — captura el contrato que el refactor C5 P2 (inline
    // delta+sign+UPSERT) debe preservar al eliminar la delegación al legacy.
    //
    // Setup discriminante: dos journals balanced con direcciones opuestas por
    // cuenta (J1 asset debit / liab credit; J2 asset credit / liab debit) →
    // debitTotal Y creditTotal ambos no-cero por cuenta. Sin paso 3, balance
    // queda 0 (default Prisma create); sin sign por nature, ACREEDORA daría
    // -70 en lugar del esperado 70.

    const j1 = buildPostedJournal();
    const j2 = buildOffsettingJournal("30");

    await prisma.$transaction(async (tx) => {
      const repo = new PrismaAccountBalancesRepo(tx);
      await repo.applyPost(j1);
      await repo.applyPost(j2);
    });

    const balances = await prisma.accountBalance.findMany({
      where: { organizationId: testOrgId, periodId: testPeriodId },
      orderBy: { account: { code: "asc" } },
    });

    expect(balances.length).toBe(2);

    // Asset (DEUDORA): debitTotal=100, creditTotal=30 → balance = 100 - 30 = 70
    expect(balances[0].accountId).toBe(assetAccountId);
    expect(balances[0].debitTotal.toString()).toBe("100");
    expect(balances[0].creditTotal.toString()).toBe("30");
    expect(balances[0].balance.toString()).toBe("70");

    // Liability (ACREEDORA): debitTotal=30, creditTotal=100 → balance = 100 - 30 = 70
    expect(balances[1].accountId).toBe(liabilityAccountId);
    expect(balances[1].debitTotal.toString()).toBe("30");
    expect(balances[1].creditTotal.toString()).toBe("100");
    expect(balances[1].balance.toString()).toBe("70");
  });
});
