import type {
  BaseScope,
  UnitOfWork,
} from "@/modules/shared/domain/ports/unit-of-work";
import type { AccountingReaderPort } from "@/modules/monthly-close/domain/ports/accounting-reader.port";
import type { PeriodLockingWriterPort } from "@/modules/monthly-close/domain/ports/period-locking-writer.port";
import type { FiscalYearWriterTxPort } from "../domain/ports/fiscal-year-writer-tx.port";
import type { YearAccountingReaderTxPort } from "../domain/ports/year-accounting-reader-tx.port";
import type { AnnualClosingJournalWriterTxPort } from "../domain/ports/annual-closing-journal-writer-tx.port";
import type { PeriodAutoCreatorTxPort } from "../domain/ports/period-auto-creator-tx.port";

/**
 * Annual-close-specific UoW scope. Tx-bound ports owned/consumed by
 * annual-close-hex `close()` use case enter via scope-membership (R5 NO
 * Prisma leak — port signatures stay domain-pure; the Phase 4 adapter
 * wires `Prisma.TransactionClient` into each port instance).
 *
 * **Cross-module REUSE under R3 (consumer-driven)** — design rev 2 §4
 * mandates direct port reuse to keep composition flat (one TX, one
 * `correlationId`, one audit context). Composing `MonthlyCloseService`
 * directly would trigger nested-tx + re-`setAuditContext` (architectural
 * trap documented in design §4):
 *
 *   - `accounting: AccountingReaderPort`  — REUSE from monthly-close.
 *     Same INSIDE-TX `sumDebitCredit` shape (per-period); annual-close also
 *     keeps a year-aggregate variant via `yearAccountingTx` for the
 *     unconditional C-1/C-4 gate.
 *   - `locking: PeriodLockingWriterPort`  — REUSE from monthly-close.
 *     Five-method cascade (Dispatch → Payment → JE → Sale → Purchase) used
 *     to lock December on the standard close path; STRICT ORDER preserved
 *     at the service layer (REQ-2.2 step 5).
 *
 * **Annual-close OWNED ports** (NEW under R2):
 *   - `fiscalYears: FiscalYearWriterTxPort` — guarded markClosed (W-3).
 *   - `yearAccountingTx: YearAccountingReaderTxPort` — TOCTOU re-reads +
 *     year-aggregate Tx + CC/CA source queries (C-3 delta-from-prior-CA).
 *   - `closingJournals: AnnualClosingJournalWriterTxPort` — CC/CA insert
 *     + REQ-2.7 port-level period-status invariant (C-5) + W-1 correlative.
 *   - `periodAutoCreator: PeriodAutoCreatorTxPort` — year+1 bulk create
 *     (REQ-5.1) + audit-trigger contingency (W-4).
 *
 * **BaseScope inherited** (cumulative POC #9 shared):
 *   - `fiscalPeriods: FiscalPeriodsTxRepo` — markClosed for Dec on the
 *     standard close path (spec REQ-2.2 step 5).
 *   - `correlationId: string` — generated by the adapter PRE-TX, propagated
 *     to all audit rows via PL/pgSQL triggers post `setAuditContext`.
 *
 * **AuditContext** is passed as PARAMETER of `UoW.run(ctx, fn)` — the
 * Phase 4 adapter invokes `setAuditContext` automatically INSIDE the TX.
 * `justification` is REQUIRED for annual-close (spec REQ-2.1 + AuditContext
 * `justification?` — required for LOCKED-document mutations).
 *
 * **TX timeout 60 s** (annual is heavier than monthly 30 s — design rev 2 §5
 * S-4). `SET LOCAL lock_timeout = '5s'` + `SET LOCAL statement_timeout = '55s'`
 * issued at TX entry by the adapter (bounds row-lock waits + runaway
 * aggregator queries).
 */
export interface AnnualCloseScope extends BaseScope {
  readonly fiscalYears: FiscalYearWriterTxPort;
  readonly yearAccountingTx: YearAccountingReaderTxPort;
  readonly closingJournals: AnnualClosingJournalWriterTxPort;
  readonly periodAutoCreator: PeriodAutoCreatorTxPort;
  readonly accounting: AccountingReaderPort;
  readonly locking: PeriodLockingWriterPort;
}

export type AnnualCloseUnitOfWork = UnitOfWork<AnnualCloseScope>;
